/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BulkClassifyUtterance : The user input utterance to classify.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkClassifyUtterance {
    /// The text of the input utterance.
    #[serde(rename = "text")]
    pub text: String,
}

impl BulkClassifyUtterance {
    /// The user input utterance to classify.
    pub fn new(text: String) -> BulkClassifyUtterance {
        BulkClassifyUtterance {
            text,
        }
    }
}


