/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkClassifyInput {
    /// An array of input utterances to classify.
    #[serde(rename = "input")]
    pub input: Vec<crate::models::BulkClassifyUtterance>,
}

impl BulkClassifyInput {
    pub fn new(input: Vec<crate::models::BulkClassifyUtterance>) -> BulkClassifyInput {
        BulkClassifyInput {
            input,
        }
    }
}


