/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CaptureGroup {
    /// A recognized capture group for the entity.
    #[serde(rename = "group")]
    pub group: String,
    /// Zero-based character offsets that indicate where the entity value begins and ends in the input text.
    #[serde(rename = "location", skip_serializing_if = "Option::is_none")]
    pub location: Option<Vec<i32>>,
}

impl CaptureGroup {
    pub fn new(group: String) -> CaptureGroup {
        CaptureGroup {
            group,
            location: None,
        }
    }
}


