/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelTransferTargetChat : Information for transferring to the web chat integration.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelTransferTargetChat {
    /// The URL of the target web chat.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl ChannelTransferTargetChat {
    /// Information for transferring to the web chat integration.
    pub fn new() -> ChannelTransferTargetChat {
        ChannelTransferTargetChat {
            url: None,
        }
    }
}


