/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ChannelTransferTarget : An object specifying target channels available for the transfer. Each property of this object represents an available transfer target. Currently, the only supported property is **chat**, representing the web chat integration.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelTransferTarget {
    #[serde(rename = "chat", skip_serializing_if = "Option::is_none")]
    pub chat: Option<Box<crate::models::ChannelTransferTargetChat>>,
}

impl ChannelTransferTarget {
    /// An object specifying target channels available for the transfer. Each property of this object represents an available transfer target. Currently, the only supported property is **chat**, representing the web chat integration.
    pub fn new() -> ChannelTransferTarget {
        ChannelTransferTarget {
            chat: None,
        }
    }
}


