/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogNodesVisited {
    /// A dialog node that was triggered during processing of the input message.
    #[serde(rename = "dialog_node", skip_serializing_if = "Option::is_none")]
    pub dialog_node: Option<String>,
    /// The title of the dialog node.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The conditions that trigger the dialog node.
    #[serde(rename = "conditions", skip_serializing_if = "Option::is_none")]
    pub conditions: Option<String>,
}

impl DialogNodesVisited {
    pub fn new() -> DialogNodesVisited {
        DialogNodesVisited {
            dialog_node: None,
            title: None,
            conditions: None,
        }
    }
}


