/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DialogNodeOutputConnectToAgentTransferInfo : Routing or other contextual information to be used by target service desk systems.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogNodeOutputConnectToAgentTransferInfo {
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<::std::collections::HashMap<String, ::std::collections::HashMap<String, serde_json::Value>>>,
}

impl DialogNodeOutputConnectToAgentTransferInfo {
    /// Routing or other contextual information to be used by target service desk systems.
    pub fn new() -> DialogNodeOutputConnectToAgentTransferInfo {
        DialogNodeOutputConnectToAgentTransferInfo {
            target: None,
        }
    }
}


