/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DialogNodeOutputOptionsElementValue : An object defining the message input to be sent to the assistant if the user selects the corresponding option.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogNodeOutputOptionsElementValue {
    #[serde(rename = "input", skip_serializing_if = "Option::is_none")]
    pub input: Option<Box<crate::models::MessageInput>>,
}

impl DialogNodeOutputOptionsElementValue {
    /// An object defining the message input to be sent to the assistant if the user selects the corresponding option.
    pub fn new() -> DialogNodeOutputOptionsElementValue {
        DialogNodeOutputOptionsElementValue {
            input: None,
        }
    }
}


