/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogNodeOutputOptionsElement {
    /// The user-facing label for the option.
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "value")]
    pub value: Box<crate::models::DialogNodeOutputOptionsElementValue>,
}

impl DialogNodeOutputOptionsElement {
    pub fn new(label: String, value: crate::models::DialogNodeOutputOptionsElementValue) -> DialogNodeOutputOptionsElement {
        DialogNodeOutputOptionsElement {
            label,
            value: Box::new(value),
        }
    }
}


