/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DialogLogMessage : Dialog log message details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogLogMessage {
    /// The severity of the log message.
    #[serde(rename = "level")]
    pub level: Level,
    /// The text of the log message.
    #[serde(rename = "message")]
    pub message: String,
    /// A code that indicates the category to which the error message belongs.
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<Box<crate::models::LogMessageSource>>,
}

impl DialogLogMessage {
    /// Dialog log message details.
    pub fn new(level: Level, message: String, code: String) -> DialogLogMessage {
        DialogLogMessage {
            level,
            message,
            code,
            source: None,
        }
    }
}

/// The severity of the log message.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Level {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "warn")]
    Warn,
}

