/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// General description of an error.
    #[serde(rename = "error")]
    pub error: String,
    /// Collection of specific constraint violations associated with the error.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::ErrorDetail>>,
    /// HTTP status code for the error response.
    #[serde(rename = "code")]
    pub code: i32,
}

impl ErrorResponse {
    pub fn new(error: String, code: i32) -> ErrorResponse {
        ErrorResponse {
            error,
            errors: None,
            code,
        }
    }
}


