/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LogMessageSourceDialogNode : An object that identifies the dialog element that generated the error message.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogMessageSourceDialogNode {
    /// A string that indicates the type of dialog element that generated the error message.
    #[serde(rename = "type")]
    pub _type: String,
    /// The unique identifier of the dialog node that generated the error message.
    #[serde(rename = "dialog_node")]
    pub dialog_node: String,
}

impl LogMessageSourceDialogNode {
    /// An object that identifies the dialog element that generated the error message.
    pub fn new(_type: String, dialog_node: String) -> LogMessageSourceDialogNode {
        LogMessageSourceDialogNode {
            _type,
            dialog_node,
        }
    }
}


