/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LogPagination : The pagination data for the returned objects.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogPagination {
    /// The URL that will return the next page of results, if any.
    #[serde(rename = "next_url", skip_serializing_if = "Option::is_none")]
    pub next_url: Option<String>,
    /// Reserved for future use.
    #[serde(rename = "matched", skip_serializing_if = "Option::is_none")]
    pub matched: Option<i32>,
    /// A token identifying the next page of results.
    #[serde(rename = "next_cursor", skip_serializing_if = "Option::is_none")]
    pub next_cursor: Option<String>,
}

impl LogPagination {
    /// The pagination data for the returned objects.
    pub fn new() -> LogPagination {
        LogPagination {
            next_url: None,
            matched: None,
            next_cursor: None,
        }
    }
}


