/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogCollection {
    /// An array of objects describing log events.
    #[serde(rename = "logs")]
    pub logs: Vec<crate::models::Log>,
    #[serde(rename = "pagination")]
    pub pagination: Box<crate::models::LogPagination>,
}

impl LogCollection {
    pub fn new(logs: Vec<crate::models::Log>, pagination: crate::models::LogPagination) -> LogCollection {
        LogCollection {
            logs,
            pagination: Box::new(pagination),
        }
    }
}


