/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LogMessageSourceStep : An object that identifies the dialog element that generated the error message.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LogMessageSourceStep {
    /// A string that indicates the type of dialog element that generated the error message.
    #[serde(rename = "type")]
    pub _type: String,
    /// The unique identifier of the action that generated the error message.
    #[serde(rename = "action")]
    pub action: String,
    /// The unique identifier of the step that generated the error message.
    #[serde(rename = "step")]
    pub step: String,
}

impl LogMessageSourceStep {
    /// An object that identifies the dialog element that generated the error message.
    pub fn new(_type: String, action: String, step: String) -> LogMessageSourceStep {
        LogMessageSourceStep {
            _type,
            action,
            step,
        }
    }
}


