/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MessageInputOptionsSpelling : Spelling correction options for the message. Any options specified on an individual message override the settings configured for the skill.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageInputOptionsSpelling {
    /// Whether to use spelling correction when processing the input. If spelling correction is used and **auto_correct** is `true`, any spelling corrections are automatically applied to the user input. If **auto_correct** is `false`, any suggested corrections are returned in the **output.spelling** property.  This property overrides the value of the **spelling_suggestions** property in the workspace settings for the skill.
    #[serde(rename = "suggestions", skip_serializing_if = "Option::is_none")]
    pub suggestions: Option<bool>,
    /// Whether to use autocorrection when processing the input. If this property is `true`, any corrections are automatically applied to the user input, and the original text is returned in the **output.spelling** property of the message response. This property overrides the value of the **spelling_auto_correct** property in the workspace settings for the skill.
    #[serde(rename = "auto_correct", skip_serializing_if = "Option::is_none")]
    pub auto_correct: Option<bool>,
}

impl MessageInputOptionsSpelling {
    /// Spelling correction options for the message. Any options specified on an individual message override the settings configured for the skill.
    pub fn new() -> MessageInputOptionsSpelling {
        MessageInputOptionsSpelling {
            suggestions: None,
            auto_correct: None,
        }
    }
}


