/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MessageInputOptionsAutoLearn : Autolearning options for the message.  **Note:** Autolearning is a beta feature.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageInputOptionsAutoLearn {
    /// Whether the message should be used for autolearning. Specify `false` to exclude a message from autolearning (for example, if you are running tests on a production assistant). If autolearning is not enabled for the dialog skill, this option is ignored.
    #[serde(rename = "learn", skip_serializing_if = "Option::is_none")]
    pub learn: Option<bool>,
    /// Whether the autolearned model should be applied when responding to the message. You can use this option to compare responses with and without autolearning. If autolearning is not enabled for the dialog skill, this option is ignored.
    #[serde(rename = "apply", skip_serializing_if = "Option::is_none")]
    pub apply: Option<bool>,
}

impl MessageInputOptionsAutoLearn {
    /// Autolearning options for the message.  **Note:** Autolearning is a beta feature.
    pub fn new() -> MessageInputOptionsAutoLearn {
        MessageInputOptionsAutoLearn {
            learn: None,
            apply: None,
        }
    }
}


