/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RuntimeEntityRole : An object describing the role played by a system entity that is specifies the beginning or end of a range recognized in the user input. This property is included only if the new system entities are enabled for the skill.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeEntityRole {
    /// The relationship of the entity to the range.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
}

impl RuntimeEntityRole {
    /// An object describing the role played by a system entity that is specifies the beginning or end of a range recognized in the user input. This property is included only if the new system entities are enabled for the skill.
    pub fn new() -> RuntimeEntityRole {
        RuntimeEntityRole {
            _type: None,
        }
    }
}

/// The relationship of the entity to the range.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "date_from")]
    DateFrom,
    #[serde(rename = "date_to")]
    DateTo,
    #[serde(rename = "number_from")]
    NumberFrom,
    #[serde(rename = "number_to")]
    NumberTo,
    #[serde(rename = "time_from")]
    TimeFrom,
    #[serde(rename = "time_to")]
    TimeTo,
}

