/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RuntimeIntent : An intent identified in the user input.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeIntent {
    /// The name of the recognized intent.
    #[serde(rename = "intent")]
    pub intent: String,
    /// A decimal percentage that represents Watson's confidence in the intent.
    #[serde(rename = "confidence")]
    pub confidence: f64,
}

impl RuntimeIntent {
    /// An intent identified in the user input.
    pub fn new(intent: String, confidence: f64) -> RuntimeIntent {
        RuntimeIntent {
            intent,
            confidence,
        }
    }
}


