/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RuntimeEntityAlternative : An alternative value for the recognized entity.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuntimeEntityAlternative {
    /// The entity value that was recognized in the user input.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// A decimal percentage that represents Watson's confidence in the recognized entity.
    #[serde(rename = "confidence", skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f32>,
}

impl RuntimeEntityAlternative {
    /// An alternative value for the recognized entity.
    pub fn new() -> RuntimeEntityAlternative {
        RuntimeEntityAlternative {
            value: None,
            confidence: None,
        }
    }
}


