/*
 * Watson Assistant v2
 *
 * The IBM Watson&trade; Assistant service combines machine learning, natural language understanding, and an integrated dialog editor to create conversation flows between your apps and your users.  The Assistant v2 API provides runtime methods your client application can use to send user input to an assistant and receive a response.
 *
 * The version of the OpenAPI document: 2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SessionResponse {
    /// The session ID.
    #[serde(rename = "session_id")]
    pub session_id: String,
}

impl SessionResponse {
    pub fn new(session_id: String) -> SessionResponse {
        SessionResponse {
            session_id,
        }
    }
}


