/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AccountSettingsRequest : Input body parameters for the Account Settings REST request.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccountSettingsRequest {
    /// Defines whether or not creating a Service Id is access controlled. Valid values:   * RESTRICTED - to apply access control   * NOT_RESTRICTED - to remove access control   * NOT_SET - to unset a previously set value
    #[serde(rename = "restrict_create_service_id", skip_serializing_if = "Option::is_none")]
    pub restrict_create_service_id: Option<RestrictCreateServiceId>,
    /// Defines whether or not creating platform API keys is access controlled. Valid values:   * RESTRICTED - to apply access control   * NOT_RESTRICTED - to remove access control   * NOT_SET - to 'unset' a previous set value 
    #[serde(rename = "restrict_create_platform_apikey", skip_serializing_if = "Option::is_none")]
    pub restrict_create_platform_apikey: Option<RestrictCreatePlatformApikey>,
    /// Defines the IP addresses and subnets from which IAM tokens can be created for the account.
    #[serde(rename = "allowed_ip_addresses", skip_serializing_if = "Option::is_none")]
    pub allowed_ip_addresses: Option<String>,
    /// Defines the MFA trait for the account. Valid values:   * NONE - No MFA trait set   * TOTP - For all non-federated IBMId users   * TOTP4ALL - For all users   * LEVEL1 - Email-based MFA for all users   * LEVEL2 - TOTP-based MFA for all users   * LEVEL3 - U2F MFA for all users 
    #[serde(rename = "mfa", skip_serializing_if = "Option::is_none")]
    pub mfa: Option<Mfa>,
    /// Defines the session expiration in seconds for the account. Valid values:   * Any whole number between between '900' and '86400'   * NOT_SET - To unset account setting and use service default
    #[serde(rename = "session_expiration_in_seconds", skip_serializing_if = "Option::is_none")]
    pub session_expiration_in_seconds: Option<String>,
    /// Defines the period of time in seconds in which a session will be invalidated due  to inactivity. Valid values:    * Any whole number between '900' and '7200'    * NOT_SET - To unset account setting and use service default
    #[serde(rename = "session_invalidation_in_seconds", skip_serializing_if = "Option::is_none")]
    pub session_invalidation_in_seconds: Option<String>,
    /// Defines the max allowed sessions per identity required by the account. Value values:   * Any whole number greater than 0   * NOT_SET - To unset account setting and use service default
    #[serde(rename = "max_sessions_per_identity", skip_serializing_if = "Option::is_none")]
    pub max_sessions_per_identity: Option<String>,
}

impl AccountSettingsRequest {
    /// Input body parameters for the Account Settings REST request.
    pub fn new() -> AccountSettingsRequest {
        AccountSettingsRequest {
            restrict_create_service_id: None,
            restrict_create_platform_apikey: None,
            allowed_ip_addresses: None,
            mfa: None,
            session_expiration_in_seconds: None,
            session_invalidation_in_seconds: None,
            max_sessions_per_identity: None,
        }
    }
}

/// Defines whether or not creating a Service Id is access controlled. Valid values:   * RESTRICTED - to apply access control   * NOT_RESTRICTED - to remove access control   * NOT_SET - to unset a previously set value
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RestrictCreateServiceId {
    #[serde(rename = "RESTRICTED")]
    RESTRICTED,
    #[serde(rename = "NOT_RESTRICTED")]
    NOTRESTRICTED,
    #[serde(rename = "NOT_SET")]
    NOTSET,
}
/// Defines whether or not creating platform API keys is access controlled. Valid values:   * RESTRICTED - to apply access control   * NOT_RESTRICTED - to remove access control   * NOT_SET - to 'unset' a previous set value 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RestrictCreatePlatformApikey {
    #[serde(rename = "RESTRICTED")]
    RESTRICTED,
    #[serde(rename = "NOT_RESTRICTED")]
    NOTRESTRICTED,
    #[serde(rename = "NOT_SET")]
    NOTSET,
}
/// Defines the MFA trait for the account. Valid values:   * NONE - No MFA trait set   * TOTP - For all non-federated IBMId users   * TOTP4ALL - For all users   * LEVEL1 - Email-based MFA for all users   * LEVEL2 - TOTP-based MFA for all users   * LEVEL3 - U2F MFA for all users 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mfa {
    #[serde(rename = "NONE")]
    NONE,
    #[serde(rename = "TOTP")]
    TOTP,
    #[serde(rename = "TOTP4ALL")]
    TOTP4ALL,
    #[serde(rename = "LEVEL1")]
    LEVEL1,
    #[serde(rename = "LEVEL2")]
    LEVEL2,
    #[serde(rename = "LEVEL3")]
    LEVEL3,
}

