/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CreateApiKeyRequest : Input body parameters for the Create API key V1 REST request.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateApiKeyRequest {
    /// Name of the API key. The name is not checked for uniqueness. Therefore multiple names with the same value can exist. Access is done via the UUID of the API key.
    #[serde(rename = "name")]
    pub name: String,
    /// The optional description of the API key. The 'description' property is only available if a description was provided during a create of an API key.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The iam_id that this API key authenticates.
    #[serde(rename = "iam_id")]
    pub iam_id: String,
    /// The account ID of the API key.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
    /// You can optionally passthrough the API key value for this API key. If passed, NO validation of that apiKey value is done, i.e. the value can be non-URL safe. If omitted, the API key management will create an URL safe opaque API key value. The value of the API key is checked for uniqueness. Please ensure enough variations when passing in this value.
    #[serde(rename = "apikey", skip_serializing_if = "Option::is_none")]
    pub apikey: Option<String>,
    /// Send true or false to set whether the API key value is retrievable in the future by using the Get details of an API key request. If you create an API key for a user, you must specify `false` or omit the value. We don't allow storing of API keys for users.
    #[serde(rename = "store_value", skip_serializing_if = "Option::is_none")]
    pub store_value: Option<bool>,
}

impl CreateApiKeyRequest {
    /// Input body parameters for the Create API key V1 REST request.
    pub fn new(name: String, iam_id: String) -> CreateApiKeyRequest {
        CreateApiKeyRequest {
            name,
            description: None,
            iam_id,
            account_id: None,
            apikey: None,
            store_value: None,
        }
    }
}


