/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Error : Error information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Error {
    /// Error code of the REST Exception. 
    #[serde(rename = "code")]
    pub code: String,
    /// Error message code of the REST Exception. 
    #[serde(rename = "message_code")]
    pub message_code: String,
    /// Error message of the REST Exception. Error messages are derived base on the input locale of the REST request and the available Message catalogs. Dynamic fallback to 'us-english' is happening if no message catalog is available for the provided input locale.
    #[serde(rename = "message")]
    pub message: String,
    /// Error details of the REST Exception. 
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<String>,
}

impl Error {
    /// Error information.
    pub fn new(code: String, message_code: String, message: String) -> Error {
        Error {
            code,
            message_code,
            message,
            details: None,
        }
    }
}


