/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ExceptionResponse : Response body parameters in case of error situations.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExceptionResponse {
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<Box<crate::models::ResponseContext>>,
    /// Error message code of the REST Exception. 
    #[serde(rename = "status_code")]
    pub status_code: String,
    /// List of errors that occured. 
    #[serde(rename = "errors")]
    pub errors: Vec<crate::models::Error>,
    /// Unique ID of the requst. 
    #[serde(rename = "trace", skip_serializing_if = "Option::is_none")]
    pub trace: Option<String>,
}

impl ExceptionResponse {
    /// Response body parameters in case of error situations.
    pub fn new(status_code: String, errors: Vec<crate::models::Error>) -> ExceptionResponse {
        ExceptionResponse {
            context: None,
            status_code,
            errors,
            trace: None,
        }
    }
}


