/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MfaRequirementsResponse : Response properties for MFA requirements.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MfaRequirementsResponse {
    /// MFA error.
    #[serde(rename = "error")]
    pub error: String,
    /// MFA Code.
    #[serde(rename = "code")]
    pub code: String,
    /// MFA AuthorizationToken.
    #[serde(rename = "authorizationToken")]
    pub authorization_token: String,
}

impl MfaRequirementsResponse {
    /// Response properties for MFA requirements.
    pub fn new(error: String, code: String, authorization_token: String) -> MfaRequirementsResponse {
        MfaRequirementsResponse {
            error,
            code,
            authorization_token,
        }
    }
}


