/*
 * IAM Identity Services API
 *
 * The IAM Identity Service API allows for the management of Account Settings and Identities (Service IDs, ApiKeys).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ResponseContext : Context with key properties for problem determination.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseContext {
    /// The transaction ID of the inbound REST request. 
    #[serde(rename = "transaction_id", skip_serializing_if = "Option::is_none")]
    pub transaction_id: Option<String>,
    /// The operation of the inbound REST request. 
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// The user agent of the inbound REST request. 
    #[serde(rename = "user_agent", skip_serializing_if = "Option::is_none")]
    pub user_agent: Option<String>,
    /// The URL of that cluster. 
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The instance ID of the server instance processing the request. 
    #[serde(rename = "instance_id", skip_serializing_if = "Option::is_none")]
    pub instance_id: Option<String>,
    /// The thread ID of the server instance processing the request. 
    #[serde(rename = "thread_id", skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
    /// The host of the server instance processing the request. 
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// The start time of the request. 
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    /// The finish time of the request. 
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// The elapsed time in msec. 
    #[serde(rename = "elapsed_time", skip_serializing_if = "Option::is_none")]
    pub elapsed_time: Option<String>,
    /// The cluster name. 
    #[serde(rename = "cluster_name", skip_serializing_if = "Option::is_none")]
    pub cluster_name: Option<String>,
}

impl ResponseContext {
    /// Context with key properties for problem determination.
    pub fn new() -> ResponseContext {
        ResponseContext {
            transaction_id: None,
            operation: None,
            user_agent: None,
            url: None,
            instance_id: None,
            thread_id: None,
            host: None,
            start_time: None,
            end_time: None,
            elapsed_time: None,
            cluster_name: None,
        }
    }
}


